services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: mhk-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mhk_karate
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - mhk-network

  # Node.js Backend Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: mhk-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:${MONGO_ROOT_PASSWORD}@mongodb:27017/mhk_karate?authSource=admin
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - mhk-network

  # React Frontend (for production)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: mhk-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mhk-network

volumes:
  mongodb_data:
    driver: local

networks:
  mhk-network:
    driver: bridge
