services:
  # MongoDB for development
  mongodb:
    image: mongo:7.0
    container_name: mhk-mongodb-dev
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mhk_karate
    volumes:
      - mongodb_dev_data:/data/db
    networks:
      - mhk-dev-network

volumes:
  mongodb_dev_data:
    driver: local

networks:
  mhk-dev-network:
    driver: bridge
